### ISSUE TITLE
make action compatible with node 16

### ISSUE THREAD

**Issue by McShelby** [Akkjon/Close-milestone#5]
**Is your feature request related to a problem? Please describe.**

Since a while GitHub throws warnings about deprecation of node 12:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Akkjon/close-milestone,

As per saying in the link this may become a real issue in summer 2023 when GitHub is switching completly to Node 16.

**Describe the solution you'd like**

It's maybe enough to bumpt the used Node version to 16.

**Comment by Akkjon** [comment]
Thank you for the notice.
I updates the node version in release v2.0.2
https://github.com/Akkjon/close-milestone/releases/tag/v2.0.2
